### ISSUE TITLE
How to access aws dynamodb, not local?

### ISSUE THREAD

**Issue by TerrificMao** [deptno/dynamo#11]
How to access aws dynamodb, not local? I can't find how to configure aws access key and security key.

**Comment by deptno** [comment]
Dynamon(v0.2.6) inherit terminal environment variables.

so I think you can select `AWS_PROFILE` or inject `AWS_ACCESS_KEY_ID` `AWS_SECERT_ACCESS_KEY` directly.

```
AWS_PROFILE=default dynamon
```

```
AWS_ACCESS_KEY_ID=xxxxx AWS_SECERT_ACCESS_KEY=xxxxx dynamon
```

I hope it works.
