### ISSUE TITLE
ENETUNREACH Error when listing tables using assumed role

### ISSUE THREAD

**Issue by LeoAdamek** [deptno/dynamo#14]
When selecting an AWS region, the following error is logged in the console, and no tables are listed:

```
(node:14168) UnhandledPromiseRejectionWarning: Error: connect ENETUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
(node:14168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It appears that the app is trying to connect to the EC2 metadata service, but is failing due to the app not running on EC2.

Further investigation indicates that this error happens when trying to run dynamon with an assumed role from `~/.aws/config` (I have set the env var `AWS_PROFILE` to the name of a profile which includes a `source_profile` and `role_arn` )

Any ideas why this isn't working?

**Comment by deptno** [comment]
sorry I don't know about the issue, I think `ENETUNREACH` may be network connection(WIFI?) issue
