### ISSUE TITLE
Add support for multiple AWS profiles

### ISSUE THREAD

**Issue by tscole** [deptno/dynamo#6]
- [X ] I have searched the [issues](https://github.com/deptno/dynamon/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce
1.
2.

## Your Environment
| Tech      | Version |
|-----------|---------|
| OS version|         |
| etc       |         |

**Comment by deptno** [comment]
`0.2.1` supports command environment env `AWS_PROFILE=YOURS dynamon`
