### ISSUE TITLE
DynamoDB 접속시 인증서 목록 참조 위치 문의

### ISSUE THREAD

**Issue by odumak** [deptno/dynamo#7]
- [ ] I have searched the [issues](https://github.com/deptno/dynamon/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## 문의 사항
**macOS에서 사용하는 Dynamon의 경우 DynamoDB Endpoint(dynamodb.ap-northeast-2.amazonaws.com)에 HTTPS 암호화 통신 접속 시 신뢰하는 인증기관 인증서 목록을 참조하는지 알 수 있을까요?**
- AWS-CLI의 경우 /Library/Python/2.7/site-packages/botocore/vendored/requests/cacert.pem을 확인합니다. 
- AWS Tookit의 경우에는 macOS: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/security/cacerts, Ubuntu:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts 파일을 확인해서 keytool을 이용해서 원하는 인증서를 import 할 수 있습니다.

해당 인증서 위치를 찾으려는 이유는 dynamodb를 직접 접속 하지 않고 경유해서 접속하려고 하는데 인증서 목록에 제가 만든 인증서를 추가해서 신뢰하도록 하려고 합니다.

그리고,  **dynamon 프로그램이 어떤 파일에 접근하는지 확인하는 방법이 있을까요?**
예를 들어 linux에서 사용하는 strace 같은 명령어가 macOS에서는 없더라고요. 
dtruss라는 명령어를 찾았는데 이걸 사용해도 어떤 인증서 목록 파일을 보는지 확인할 수 없었습니다.

긴글 읽어주셔서 감사합니다.

## Steps to Reproduce
1.
2.

## Your Environment
| Tech      | Version |
|-----------|---------|
| OS version|macOS High Sierra 10.13.6|
| Dynamon version | 0.1.5     |

**Comment by deptno** [comment]
credential 이 아닌 인증서 얘기군요 제 지식을 넘어가는 것 같습니다.

답변이 될런지 모르겠으나 `dynamodb.ap-northeast-2.amazonaws.com` 을 접속하면 인증서가 그 쪽에서 넘어올텐데 이게 저장되는 곳을 말씀하시는 것인가요?

인증서와 관련해서는 MacOS 쪽에서 따로 관리가 되는 것으로 알고 있으나 여기에 보이지 않는다면 다이나몬이 포함하는 브라우저의 기반인 `electron` 을 포함하여 구글링해보시는게 맞는 것 같습니다.

혹시나 모르니 이슈를 좀 더 유지하고 클로즈하겠습니다.

**Comment by odumak** [comment]
답변 감사합니다.

electron 부분을 확인하고 있는데 아직 위치를 찾지 못했습니다.

테스트를 위해서 certificate-error일 경우에도 정상적으로 동작하도록 다음 코드를 추가해서 수정하고 싶은데 해당 코드를 어디에 넣어야하는지 모르겠네요. node.js, electron을 이번에 처음봐서.. 도움을 주실 수 있을까요?

const {app} = require('electron')
  
  app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
      event.preventDefault()
      callback(true)
  })

참조: https://tinydew4.github.io/electron-ko/docs/api/app/

**Comment by deptno** [comment]
아마존 인증서가문제가 생긴다는게 언뜻 이해는 잘 가지 않는데 어떤 경우에 발생하는 이슈인가요?

혹시 문제 발생시의 화면과 이슈 재현 방법을 볼 수 있을까요?

**Comment by odumak** [comment]
일단 인증서의 경우 "키체인 접근"을 사용해서 등록하는 방법을 찾았습니다.
그래서 사파리나 크롬의 경우 쿠키 삭제 후 제가 발급한 인증서를 잘 사용하여 신뢰하도록 만드는데 문제가 없도록 만들었습니다.

하지만, electron의 경우 어떤 쿠키정보를 삭제할 수 없어 접속이 안되고 있습니다.
혹시 electron의 쿠키 정보를 삭제하는 방법을 알 수 있을까요? (프로그램 자체에는 없어 보이고, macOS 터미널 내에서 삭제하는 방법을 찾지 못했습니다.)
Dynamon APP을 휴지통에 삭제 후 재설치 해도 해당 쿠키정보가 계속 남아 있는것으로 보입니다.
쿠키 정보만 삭제되면 문제를 해결할 수 있을 것으로 판단됩니다.
(이슈 재현 방법을 전달드리고 싶으나, 방법이 마땅치 않아 전달 못드린 점 양해 부탁드립니다.)

**Comment by deptno** [comment]
이슈가 맵 앱 설치, 삭제 또는 일렉트론으로 보입니다. 이슈 닫습니다.

맥 어플 삭제에 대해서 검색해보시면 되지 않을까 합니다.
