### ISSUE TITLE
Expects Electron, Stuck in Intialization

### ISSUE THREAD

**Issue by omenking** [deptno/dynamo#8]
Trying to run the app, electron fails to run.
My buddy and I both on different OS having the same issue attempting to run this web-app.
Tried install electron globally but to no avail.

![screen shot 2018-10-23 at 10 29 59 pm](https://user-images.githubusercontent.com/7776/47402384-44989180-d713-11e8-9cbf-7abd9471b61b.png)

![screen shot 2018-10-23 at 10 31 02 pm](https://user-images.githubusercontent.com/7776/47402399-5e39d900-d713-11e8-83ca-307278fb8bad.png)

**Comment by deptno** [comment]
```
npm -g i dynamon
dynamon
```

I've deploy `0.2.1` It's built on next.js not electron, dynamon supports only few feature. sorry for late response.

**Comment by omenking** [comment]
Thanks I'll give it a try
